Implemented partial sum cache for SMAIndicator
ta4j/ta4j pull request #1140
Opened 2024-03-28 06:17 UTC by sgflt

Fixes #.

Performance of partial sums.

Changes proposed in this pull request:
- longer barSeries benefits from reusage of precomputed partial sums
- random access fallbacks to slowPath

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

2024-03-28 06:18 UTC, sgflt commented
Test on real data:
**Before:**
ta4jexamples.backtesting.MovingAverageCrossOverRangeBacktest -- Back-tested 2145 strategies on 6150-bar series in 72520 ms


**After:**
ta4jexamples.backtesting.MovingAverageCrossOverRangeBacktest -- Back-tested 2145 strategies on 6150-bar series in 6222 ms

2024-03-29 13:07 UTC, TheCookieLab requested changes

2024-03-29 13:07 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/indicators/SMAIndicator.java
> +    private Num previsouSum = zero();
```suggestion
    private Num previousSum = zero();
```

2024-04-03 09:53 UTC, sgflt commented
I will add edge case tests, to prove functionality.

2024-04-03 11:19 UTC, sgflt commented
Umm, what is expected behavior for moving series?

If I add following test:

```java
    @Test
    public void usingBarCount3UsingClosePriceMovingSerie() {
        data.setMaximumBarCount(13);
        data.addBar(new MockBar(5., numFunction));

        Indicator<Num> indicator = getIndicator(new ClosePriceIndicator(data), 3);

        assertNumEquals((0d + 0d + 2d) / 1, indicator.getValue(data.getBeginIndex() + 0));
        assertNumEquals((0d + 2d + 3d) / 2, indicator.getValue(data.getBeginIndex() + 1));
        assertNumEquals((2d + 3d + 4d) / 3, indicator.getValue(data.getBeginIndex() + 2));
        assertNumEquals((3d + 4d + 3d) / 3, indicator.getValue(data.getBeginIndex() + 3));
    }

```


It fails on second assert (0d + 2d + 3d) / 2 even with previous implementation.

```
Expected :2.5
Actual   :2.3333333333333335
```

2024-04-08 06:22 UTC, sgflt commented
Discovered RunningTotalIndicator. I may use this indicator as partialSum and optimize RunningTotalIndicator.

2024-04-14 05:20 UTC, sgflt commented
And now I have discovered PreviousValueIndicator. I think I may combine them too.

2024-04-17 13:58 UTC, sgflt commented
Nope with indexes.

2024-05-09 13:25 UTC, TheCookieLab commented
Yes, you'll want to handle unstable indexes as unstable and assert accordingly.

2024-05-09 13:28 UTC, TheCookieLab commented
@sgflt please run the formatter (`mvn -B clean license:format formatter:format test`) and re-push

2024-05-17 14:42 UTC, TheCookieLab approved these changes

2024-05-17 14:44 UTC, TheCookieLab commented
@sgflt I recently cut the 0.16 release and started 0.17. Can you update your CHANGELOG entry accordingly? Thanks.

2024-05-19 10:50 UTC, sgflt commented
Done

2024-05-19 16:52 UTC, TheCookieLab approved these changes

2024-05-19 16:52 UTC, merged