Candle indicators
ta4j/ta4j pull request #1146
Opened 2024-04-07 11:22 UTC by sgflt

Fixes #1145.

Changes proposed in this pull request:
- HammerIndicator
- InvertedHammerIndicator
- HangingManIndicator
- DownTrendIndicator
- UpTrendIndicator

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

2024-05-09 13:05 UTC, TheCookieLab requested changes

2024-05-09 13:05 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/indicators/trend/DownTrendIndicator.java
> +    private static final int UNSTABLE_BARS = 5;
The choice of 5 here is unnecessarily opinionated no? How about as a constructor param?

2024-05-09 13:05 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/indicators/trend/UpTrendIndicator.java
> +    private static final int UNSTABLE_BARS = 5;
Same as above

2024-05-09 13:05 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/indicators/candles/HammerIndicator.java
> +    private static final double BODY_LENGTH_TO_BOTTOM_WICK_COEFFICIENT = 2d;
Should these be constructor params rather than hardcoded?

2024-05-09 13:05 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/indicators/candles/HangingManIndicator.java
> +    private static final double BODY_LENGTH_TO_BOTTOM_WICK_COEFFICIENT = 2d;
Same as above. Perhaps these values can be used as defaults in a no-arg constructor.

2024-08-22 18:58 UTC, btezergil commented
Hello @sgflt, do you intend to continue working on this? The changes proposed here would be quite useful to me as I'm also trying to use hammer/inverted hammer indicators. If you do not intend to continue, I can implement the requested changes. I also need shooting star indicator as well and I can add that too.

2024-08-23 18:35 UTC, btezergil commented
Thanks @sgflt , can you please give me contributor rights to your fork, or should I copy your changes into a fork of mine?

2024-08-23 18:42 UTC, sgflt commented
You can fork this repo, add second remote as my repo and fetch branch from it. It should preserve history.

2024-08-30 18:18 UTC, closed without merging