fix VersusEnterAndHoldCriterion
ta4j/ta4j pull request #1195
Opened 2024-10-11 21:22 UTC by nimo23

Fixes https://github.com/ta4j/ta4j/issues/1073

Changes proposed in this pull request:
- Consider `base` when calculating `ReturnCriterion` of a position.
- Fixed calculation for `VersusEnterAndHoldCriterion`

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

2024-10-30 18:51 UTC, TheCookieLab requested changes

2024-10-30 18:51 UTC, TheCookieLab commented on ta4j-core/src/main/java/org/ta4j/core/criteria/VersusEnterAndHoldCriterion.java
> + * <li>ProfitLossPercentageVsEnterAndHold = (0.9 - (-0.3)) / abs(-0.3) = +4 (=
Why is 20% less than enter-and-hold represented by -0.2? Shouldn't it be 0.8? 

This is exactly why the same class producing semantically different values via a `addBase` flag introduces needless complexity and defect potential. That the examples in this javadoc mix them up says it all.

Any solution needs to include splitting the `ReturnCriterion` into separate classes.

2024-10-30 19:33 UTC, nimo23 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/VersusEnterAndHoldCriterion.java
> + * <li>ProfitLossPercentageVsEnterAndHold = (0.9 - (-0.3)) / abs(-0.3) = +4 (=
>Why is 20% less than enter-and-hold represented by -0.2? Shouldn't it be 0.8?

No, it is 20 less, because x is just 20% worse than enter and hold. You only care about the `signed difference of x and enterAndHold`. If both are not different then 0 is returned.

By the way, if you were to say "it's 0.8" then firstly that doesn't tell you how much worse oder better x is and secondly, most importantly, it would simply lead to incorrect calculations (even without a `addBase`) because It would ignore `+` and `–` and give an incorrect result for many criteria. Moreover, this fix is ​​stable to `addBase` as it would give the same result whether base is used or not. 

>This is exactly why the same class producing semantically different values via a addBase flag introduces needless complexity and defect potential. That the examples in this javadoc mix them up says it all.

Yes, I am with you. But actually we need to solve the current issue and therefore, the `base` should stay at the moment - no need for breaking changes here. My PR is only about bug fixing. Please re-read https://github.com/ta4j/ta4j/pull/1197#issuecomment-2426962927. 

> If you are unable or unwilling to do it 

No, I am not unwilling to do it. I also want to do it and create another class. But after this bug fix. We need a clean branch and improve that. Don't mess things up. Re-read https://github.com/ta4j/ta4j/pull/1197#issuecomment-2426962927.

Btw, you should be more aware of the consequences of removing the base for other classes or code bases..

2025-06-18 12:46 UTC, nimo23 commented
Replaced by https://github.com/ta4j/ta4j/pull/1282

2025-06-18 12:46 UTC, closed without merging