Added an example Gson serialization to store or load a given Series t…
ta4j/ta4j pull request #726
Opened 2021-04-16 08:31 UTC by MarcDahlem

…o json

Fixes #.

Changes proposed in this pull request:
- added an example Gson de-/serialization for BarSeries

- [ ] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

2021-04-16 08:55 UTC, MarcDahlem commented
Oh well, that failed test run is interesting. It randomly picked one index, which does not need the bigInteger precession.
As I also worked with the Interface "Number" in the Gson-Wrapper-Classes, Gson treats the number as double value instead of BigDecimals.

How should I proceed here?
a) Is the (Base)BarSeries able to contain some bars as BigDecimal and others as double or even integer? (This would mean I could just fix the tests).
b) Or should I force Gson to always produce BigDecimals while adding a new bar to the created bar series?

2021-04-16 11:31 UTC, MarcDahlem commented
Okay, nevermind.
The test alone runs fine on all elements; only if executed with all other tests together it didnt work.

Someone thought that changing the defaultfunction in the BarSeriesTest (main-method in ta4jexamples/barSeries/BuildBarSeries.java ) was a good idea...

I made this BuildBarSeries reset the defaultFunction to ensure correct behaviour for all tests running afterwards

2021-04-20 20:10 UTC, team172011 requested changes
Thanks for the PR. But this example is mostly based on a third party library that I do not want to add as a dependency to this lib

2021-04-20 21:26 UTC, MarcDahlem commented
Its just in the examples. Dont you consider this as better than having no code at all available how to store a data series in a useful format?
Which json library would you prefer over gson? Moshi? Jackson?

2021-05-01 13:19 UTC, team172011 approved these changes

2021-05-01 13:19 UTC, team172011 commented on CHANGELOG.md
> +- **Example** added a json serialization and deserialization example of BarSeries
Please add using google-gson library

2021-05-01 13:20 UTC, team172011 commented
Okay, please resolve conflicts and I will merge this example. I think it adds value to the example project in the same way like plotting data using the jFreeCharts library

2021-05-02 08:33 UTC, MarcDahlem commented on CHANGELOG.md
> +- **Example** added a json serialization and deserialization example of BarSeries
done

2021-05-02 12:45 UTC, team172011 approved these changes

2021-05-02 12:45 UTC, merged