Criteria: add lessBetter to dedicated criteria
ta4j/ta4j pull request #960
Opened 2023-04-14 23:24 UTC by nimo23

Fixes https://github.com/ta4j/ta4j/issues/957.

Changes proposed in this pull request:
- added "lessBetter"-property for **AverageCriterion**
- added "lessBetter"-property for **RelativeStandardDeviation**
- added "lessBetter"-property for **StandardDeviationCriterion**
- added "lessBetter"-property for **StandardErrorCriterion**
- added "lessBetter"-property for **VarianceCriterion**
- added "lessBetter"-property for **NumberOfPositionsCriterion**

- [x] added an entry with related ticket number(s) to the unreleased section of `CHANGES.md`

2023-04-15 09:23 UTC, team172011 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/NumberOfPositionsCriterion.java
> +                : criterionValue1.isGreaterThan(criterionValue2);
What about using an `int` for the `lessBetter` variable (for instance 0 or -1) and comparing the criterion values with `num.compareTo(num2) < lessBetter`

2023-04-15 21:13 UTC, nimo23 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/NumberOfPositionsCriterion.java
> +                : criterionValue1.isGreaterThan(criterionValue2);
What is the benefit in using `Num#compareTo` directly instead of `Num#isLessThan` or `Num#isGreaterThan ` (which also calls `Num#compareTo`).  I cannot imagine that there is any performance gains.

Btw, using a `boolean` property in constructor is more intuitive than using -1,+1..

2023-04-16 08:02 UTC, nimo23 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/NumberOfPositionsCriterion.java
> +                : criterionValue1.isGreaterThan(criterionValue2);
@team172011 Using `int lessBetter` results in this code:

```
/**
 * Average criterion.
 * 
 * <p>
 * Calculates the average of a Criterion by dividing it by the number of
 * positions.
 */
public class AverageCriterion extends AbstractAnalysisCriterion {

    /**
     * If {@code 0}, then the lower the criterion value the better. If {@code -1}, 
     * then the higher the criterion value the better. This property is only used for
     * {@link #betterThan(Num, Num)}.
     */
    private final int lessBetter;

    private final AnalysisCriterion criterion;
    private final NumberOfPositionsCriterion numberOfPositionsCriterion = new NumberOfPositionsCriterion();

    /**
     * Constructor with {@link #lessBetter} == false.
     * 
     * @param criterion the criterion from which the "average" is calculated
     */
    public AverageCriterion(AnalysisCriterion criterion) {
        this.criterion = criterion;
        this.lessBetter = -1;
    }

    /**
     * Constructor.
     * 
     * @param criterion  the criterion from which the "average" is calculated
     * @param lessBetter if true, then sets {@link #lessBetter} to {@code 0}, otherwise to {@code -1}
     */
    public AverageCriterion(AnalysisCriterion criterion, boolean lessBetter) {
        this.criterion = criterion;
        this.lessBetter = lessBetter ? 0 : -1;
    }

    @Override
    public Num calculate(BarSeries series, Position position) {
        Num numberOfPositions = numberOfPositionsCriterion.calculate(series, position);
        return criterion.calculate(series, position).dividedBy(numberOfPositions);
    }

    @Override
    public Num calculate(BarSeries series, TradingRecord tradingRecord) {
        if (tradingRecord.getPositions().isEmpty()) {
            return series.zero();
        }
        Num numberOfPositions = numberOfPositionsCriterion.calculate(series, tradingRecord);
        return criterion.calculate(series, tradingRecord).dividedBy(numberOfPositions);
    }

    /**
     * If {@link #lessBetter} == false, then the lower the criterion value, the
     * better, otherwise the higher the criterion value the better.
     */
    @Override
    public boolean betterThan(Num criterionValue1, Num criterionValue2) {
        return criterionValue1.compareTo(criterionValue2) > lessBetter;
    }

}
```


Is using `int lessBetter` instead of `boolean lessBetter` really better? 
I know I would bypass a method  call(`Num#isLessThan`/`Num#isBetterThan`) and bypass an additional check for `NaN` if I use `int lessBetter`. But is it worth it in terms of measurable performance?

2023-04-17 14:36 UTC, team172011 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/NumberOfPositionsCriterion.java
> +                : criterionValue1.isGreaterThan(criterionValue2);
I do not know if it is better or not. I like to reduce the amount of if-else statements or ternary operators if possible. I think it is just a matter of taste and I am also ok with this approach

2023-04-17 16:52 UTC, TheCookieLab commented
I feels like we are trying to band-aid over a design contradiction. An interface function should be universally applicable but given we now have a significant sub-set of criteria where the concept of "better than" is either ambiguous, subjective, or non-applicable it raises the question of whether we should continue down this path of increasing complexity or would it be cleaner to remove the betterThan function altogether and let the client compare the num values directly?

2023-04-17 18:01 UTC, nimo23 commented on ta4j-core/src/main/java/org/ta4j/core/criteria/NumberOfPositionsCriterion.java
> +                : criterionValue1.isGreaterThan(criterionValue2);
I do not like the idea to give to user an `int` as a choice because an `int` can have other values than `0` and `-1`. Thus, it is better to use a `boolean`. 

@team172011 You can merge this PR. I am finished.

2023-04-17 20:20 UTC, TheCookieLab commented
I agree that "better than" should be applicable to any given criteria, but
this should be the user's responsibility, not the toolset's. The point is
that we, at the framework level, should focus on providing tools that
generate objective data while leaving interpretation to the users.
Deviating from this principle harms everyone: users, by artificially
restricting their use cases (e.g., NumberOfBarsCriterion or
LinearTransactionCostCriterion - what if the client is a broker simulating
the other side of trades?), and maintainers, by unnecessarily increasing
code complexity. Stateless functions are one thing, but adding state would
be a significant step down that slippery slope.

Philosophical concerns aside, from a practical standpoint I'm still unclear
what value this functionality provides me, as a user, over the baseline of
comparing criteria values directly. Previously one could argue that
'betterThan' abstracts the user from certain semantic knowledge, but this
proposed change would negate that altogether. If I have the necessary
semantic knowledge at runtime to set the lessBetter flag, then I have
enough knowledge to compare and interpret the values directly, which is
simpler to boot. What am I missing here?



On Mon, Apr 17, 2023 at 2:29 PM nimo23 ***@***.***> wrote:

> @TheCookieLab <https://github.com/TheCookieLab> But in once case you are
> right: The interface method hides the fact, that different types of
> criteria are not necessarly comparable (e.g. you cannot compare the Num
> value of a ProfitCriterion with the Num value of a LossCriterion). But
> who knows:)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ta4j/ta4j/pull/960#issuecomment-1511879836>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQJ6FN3A5ERSHEJVMXKHELXBWDZNANCNFSM6AAAAAAW7ADKKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-17 20:59 UTC, TheCookieLab requested changes
The changes in this fix are net-negative for the code-base's readability, consistency, and would further entrench a source of subjectivity and recurring future contention.

I would like to see a different approach, if not complete removal of the `betterThan` interface function then *something* else.

2023-04-17 22:13 UTC, TheCookieLab commented
It's certainly possible I simply don't understand betterThan's value, so
that's why I've inquired several times for use cases that would help me
understand it. I've laid out my arguments against it in what I believe to
be clear cost/benefit terms but I've yet to see a rebuttal from you that
goes further than "because I'm using it.".

On Mon, Apr 17, 2023 at 5:41 PM nimo23 ***@***.***> wrote:

> I also think that you are requesting changes here that
>
> a) first of all have nothing to do with the PR (namely the deletion of
> betterThan)
> b) and secondly that you still don't make it clear exactly what changes I
> should make (except for the deletion of betterThan, which not treated by
> this PR).
>
> Don't get me wrong, I think it's really good that you're willing to make
> this project better, but I can't see any constructive improvement here,
> just a purely subjective opinion of deleting the betterThan method since
> you have no use for it.
>
> I think it's generally not good to use your privilege for the project in
> this way. And I'm thinking about requesting such privileges from
> @team172011 <https://github.com/team172011> as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ta4j/ta4j/pull/960#issuecomment-1512119923>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQJ6FJPV6EURMQQDBSMYCDXBW2IXANCNFSM6AAAAAAW7ADKKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-17 22:55 UTC, TheCookieLab commented
Please refrain from ...reviewing PRs? Because that's what I'm doing, reviewing your PR.

Do you have any use cases demonstrating the value of `betterThan` so as to enlighten those of us who don't understand? This is the third time asking.

2023-04-17 23:47 UTC, TheCookieLab commented
Yes, if the reviewer doesn't agree with the proposed change-set then he/she is not going to approve. How do code reviews work at your job?

I've provided reasoning for why I do not agree with these changes. I've also provided rationale why I believe removing `betterThan` altogether is the best, holistic solution. If you disagree, you then provide counter-points - flaws in my premises, reasoning, etc. That's how this is supposed to work. 

The fact that you've not provided any rationale on why I'm wrong or why `betterThan` should exit leads me to believe you don't have any, and your defensiveness is due to a mix of sunk-cost fallacy and taking critique of code you wrote as a personal attack. 

As the party who first opened this issue as a bug I'd actually prefer no action over this change-set.

2023-04-18 00:47 UTC, TheCookieLab commented
It is unneeded because it provides minimal benefit over simply comparing
the criteria values directly. Code has carrying cost so all things being
equal less code is better than more code.

This fix further strains the value proposition by negating any and all of
the existing benefit while simultaneously adding additional state to
manage.

On Mon, Apr 17, 2023 at 8:02 PM nimo23 ***@***.***> wrote:

> Please spare yourself such general phrases. I told you exactly what I
> criticized. Just read my answers above again (multiple times if necessary)
> until you know what I mean. But we can also go this simple way:
>
> The fact that you've not provided any rationale on why I'm wrong or why
> betterThan
>
> It is *NOT* my responsibility to prove that a method that already exists
> should be deleted. YOU have the burden of proof, not I. But the only thing
> you bring forward as evidence that this method should be deleted is because
> YOU see no need for this method.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ta4j/ta4j/pull/960#issuecomment-1512255272>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQJ6FPTHMCZ47HDV2JN5WDXBXKZRANCNFSM6AAAAAAW7ADKKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-18 11:55 UTC, TheCookieLab commented
If it’s implementation is not known at runtime, then now can we correctly
set the ‘lessBetter’ param?

On Mon, Apr 17, 2023 at 9:29 PM nimo23 ***@***.***> wrote:

> It is unneeded because it provides minimal benefit over simply comparing
> the criteria values directly.
>
> And how should someone compare an AnalysisCriterion when it's
> implementation is not known at runtime? Please be aware, that others could
> have other requirements than you. The *minimal benefit* you assume is
> because of your lack of knowledge. Your general heuristic about *good
> software engineering* doesn't apply here.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ta4j/ta4j/pull/960#issuecomment-1512309096>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABQJ6FNE4VVQWRXZHO2JJ2TXBXU77ANCNFSM6AAAAAAW7ADKKE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-27 18:56 UTC, TheCookieLab commented
Last call for community feedback. I'm planning on merging this PR within the next day or so.

2023-05-06 00:57 UTC, merged